version: '3'
services:
  frontend:
    image: frontend:1.0
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["/bin/bash", "/app/start_frontend_server.sh"]
  backend:
    image: backend:1.0
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend/:/app
    ports: 
      - "8000:8000"
    command: ["/bin/bash", "/app/start_backend_server.sh"]

