version: '3'
services:
  frontend:
    env_file:
      - .env
    image: frontend:1.0
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: ["/bin/bash", "/app/start_frontend_server.sh"]
  backend:
    env_file:
      - .env
    image: backend:1.0
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend/:/app
    ports:
      - "${REACT_APP_BACKEND_PORT}:${REACT_APP_BACKEND_PORT}"
    command: ["/bin/bash", "/app/start_backend_server.sh"]
